meta_product_name: "Monesy App"
meta_title: "Monesy App"
meta_description: "It's a mobile web application where you can manage your budget: you have a list of transactions associated with a category, so that you can see how much money you spent and on what. Give a chance to it! You will love it!"
meta_image: "meta-img.png" # should exist in `app/assets/images/`